invent_two_numbers:
  description: >
    Come up with two new integer numbers
  expected_output: >
    The two new integer numbers
  agent: inventor

sum_two_numbers:
  description: >
    Sum up the two numbers
  expected_output: >
    The sum of the two numbers, in Portuguese
  agent: mathematician
